
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.istio.io
spec:
  group: install.istio.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
            status:
              type: object
  scope: Namespaced
  names:
    plural: istiooperators
    singular: istiooperator
    kind: IstioOperator
    shortNames:
      - iop
