apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istiod
  interval: 10m
  chart:
    spec:
      chart: gateway
      version: "1.23.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  targetNamespace: istio-system
  releaseName: istio-ingressgateway
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort
      ports:
        - name: http
          port: 80
          targetPort: 8080
          nodePort: 30080
        - name: https
          port: 443
          targetPort: 8443
          nodePort: 30443