
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  interval: 10m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: require-labels
  namespace: kyverno
data:
  require-labels.yaml: |
    apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    metadata:
      name: require-labels
    spec:
      validationFailureAction: Audit
      rules:
      - name: check-for-labels
        match:
          any:
          - resources:
              kinds:
              - Pod
        validate:
          message: "All pods must have 'app' and 'version' labels"
          pattern:
            metadata:
              labels:
                app: "?*"
                version: "?*"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno/
