apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1m
  releaseName: kyverno
  targetNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: v3.1.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    crds:
      install: true
    admissionController:
      replicas: 2
      serviceMonitor:
        enabled: false
    backgroundController:
      enabled: true
    cleanupController:
      enabled: true
    reportsController:
      enabled: true
