apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: operator
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
