
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      version: 1.21.4
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      version: 1.21.4
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 10m

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  url: https://istio.io/charts

