apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 3.1.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
  values:
    cleanupJobs:
      admissionReports:
        enabled: false
      clusterAdmissionReports:
        enabled: false
    hooks:
      enabled: false