apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: calico
  namespace: kube-system
spec:
  interval: 1m
  releaseName: calico
  targetNamespace: tigera-operator
  storageNamespace: tigera-operator
  chart:
    spec:
      chart: tigera-operator
      version: v3.28.0
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: flux-system
  values:
    installation:
      calicoNetwork:
        bgp: Disabled
        mtu: 1450
        ipPools:
          - cidr: 10.244.0.0/16
            encapsulation: VXLAN
      cni:
        type: Calico
      kubernetesProvider: ""
