---
apiVersion: v1
kind: Namespace
metadata:
  name: calico-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: calico
  namespace: calico-system
spec:
  chart:
    spec:
      chart: calico
      version: 3.26.0
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
  interval: 10m
  values:
    installation:
      kubernetesProvider: "kubeadm"
    calico-node:
      ipam:
        type: Calico
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: projectcalico
  namespace: flux-system
spec:
  interval: 1h
  url: https://projectcalico.docs.tigera.io/charts
