
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: tigera-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: tigera-operator
      version: "3.27.*"
      sourceRef:
        kind: HelmRepository
        name: calico
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
