apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calico
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tigera-operator
      version: v3.27.2
      sourceRef:
        kind: HelmRepository
        name: project-calico
        namespace: kube-system
