apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/clusters/my-cluster/infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
